title: Ciallo~
# 左侧栏名字
author_name: Coconut-Aero

# 左侧栏标签，只能两个
tag1: 可爱
tag2: 认真

# 左侧栏Github连接
github_url: https://github.com/Coconut-Aero

# 左侧栏座右铭，分两句
motto_prev: “Turn Hands up. Time to Surrender!”
motto_last: “Take Over—Lyn”

# 小站部署日期（运营时间）
public_date: 2024-6-19

favicon: /favicon.ico


# 左侧栏菜单
menu:
  - [小站首页, '/', 'icon-shouye']
  - [个人日志, '/log', 'icon-rizhi']
  - [友情链接, '/link', 'icon-youqinglianjie']
  - ['关于自己', '/about', 'icon-guanyuwomen']
  - ['我的工具', '/tools', 'icon-gongju']

# 友情连接：头像、名字、链接
links:
 - ['https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg', 'Hexo.', 'https://hexo.io/zh-cn/']

# 右侧栏公告
notice: 你们好呀 我是Coconut Aero! 希望能在一起度过快乐的时光~

# 右侧音乐列表：歌名、作者、链接、封面
musics:
  - [' Cat', 'C418', 'music/C418 - Cat.mp3', 'https://p1.music.126.net/yWGWC5bU09lXNKGJm8xMKQ==/109951167354263334.jpg?param=130y130']
  - [' Haggstrom', 'C418', 'music/C418 - Haggstrom.mp3', 'https://p1.music.126.net/yWGWC5bU09lXNKGJm8xMKQ==/109951167354263334.jpg?param=130y130']
  - [' Moog City 2', 'C418', 'music/C418 - Moog City 2.mp3', 'https://p1.music.126.net/yWGWC5bU09lXNKGJm8xMKQ==/109951167354263334.jpg?param=130y130']
  - [' Subwoofer Lullaby', 'C418', 'music/C418 - Subwoofer Lullaby.mp3', 'https://p1.music.126.net/yWGWC5bU09lXNKGJm8xMKQ==/109951167354263334.jpg?param=130y130']

# 个人介绍
likes:


# 工具配置：封面，标题，介绍，链接
tools:
  # - ['https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/30e94204580a4dbd83a64d4f91a9a6e5~tplv-k3u1fbpfcp-no-mark:240:240:240:160.awebp?', 'PNG图片压缩器', '这是一款无损压缩PNG图片的在线工具，可以童工上传或拖动来批量压缩图片并打包下载', 'http://1.14.43.39:5000/']
  - ['https://coke-cola.gitee.io/resume-page/assets/dark-f439b888.jpeg', '在线简历生成器', '一个免费的在线简历生成工具', 'https://coke-cola.gitee.io/resume-page/#/']

# 右侧栏网站信息
copyright: Coconut Aero All Rights Reserved.


# 是否开启文章评论 Valine:https://valine.js.org/configuration.htm
comments:
  enable: true
  appId: 'Pf8zCXGEH1qsprnWfikVVujL-gzGzoHsz'
  appKey: 'qOqoiUHhH1TGtLRUYURkLRQX'
  placeholder: '请留下你宝贵的意见吧~'
  meta: ['nick']
  recordIP: true
  visitor: true
  enableQQ: true

# 纪念模式 none: 不设置 all：全部置灰 index: 首页置灰
gray: none

# 日志篇幅超过1000字后隐藏（最大高度为1000px)，1000可为任意数值
log_text_num: 1000

# 版本号
version: 0.0.1 Test
